// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockServicer is a mock of Servicer interface
type MockServicer struct {
	ctrl     *gomock.Controller
	recorder *MockServicerMockRecorder
}

// MockServicerMockRecorder is the mock recorder for MockServicer
type MockServicerMockRecorder struct {
	mock *MockServicer
}

// NewMockServicer creates a new mock instance
func NewMockServicer(ctrl *gomock.Controller) *MockServicer {
	mock := &MockServicer{ctrl: ctrl}
	mock.recorder = &MockServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockServicer) EXPECT() *MockServicerMockRecorder {
	return m.recorder
}

// SetTimeZone mocks base method
func (m *MockServicer) SetTimeZone(chatID int, timezone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTimeZone", chatID, timezone)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTimeZone indicates an expected call of SetTimeZone
func (mr *MockServicerMockRecorder) SetTimeZone(chatID, timezone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTimeZone", reflect.TypeOf((*MockServicer)(nil).SetTimeZone), chatID, timezone)
}
