// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	remindlist "github.com/enrico5b1b4/telegram-bot/reminder/remindlist"
	gomock "github.com/golang/mock/gomock"
)

// MockServicer is a mock of Servicer interface
type MockServicer struct {
	ctrl     *gomock.Controller
	recorder *MockServicerMockRecorder
}

// MockServicerMockRecorder is the mock recorder for MockServicer
type MockServicerMockRecorder struct {
	mock *MockServicer
}

// NewMockServicer creates a new mock instance
func NewMockServicer(ctrl *gomock.Controller) *MockServicer {
	mock := &MockServicer{ctrl: ctrl}
	mock.recorder = &MockServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockServicer) EXPECT() *MockServicerMockRecorder {
	return m.recorder
}

// GetRemindersByChatID mocks base method
func (m *MockServicer) GetRemindersByChatID(chatID int) ([]remindlist.ByJobStatusList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemindersByChatID", chatID)
	ret0, _ := ret[0].([]remindlist.ByJobStatusList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemindersByChatID indicates an expected call of GetRemindersByChatID
func (mr *MockServicerMockRecorder) GetRemindersByChatID(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemindersByChatID", reflect.TypeOf((*MockServicer)(nil).GetRemindersByChatID), chatID)
}

// RemoveCompletedReminders mocks base method
func (m *MockServicer) RemoveCompletedReminders(chatID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCompletedReminders", chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCompletedReminders indicates an expected call of RemoveCompletedReminders
func (mr *MockServicerMockRecorder) RemoveCompletedReminders(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCompletedReminders", reflect.TypeOf((*MockServicer)(nil).RemoveCompletedReminders), chatID)
}
